# data 관련 설정
image_root: /data/ephemeral/home/data/train/DCM
fold_root: /data/ephemeral/home/folds
label_root: /data/ephemeral/home/data/train/outputs_json
test_root: /data/ephemeral/home/data/test
fold_list: [0,]

# 앱 설정 정의
kakao_uuid_path: /data/ephemeral/home/keys/uuid.json
task: SegFormer
access_name: 임용섭
server: 1

# mlflow
exp_name: ys
run_name: SegFormer_100ep

# 모델명 및 사전 학습 여부
model:
  model_name: SegFormer
  model_parameter:
    in_channels: 3
    classes: 29
    pretrained: True
    start_filters: 16
    deep_supervision: False
    cgm: True

# batch_size
train_batch_size: 2
val_batch_size: 2
test_batch_size: 4


# image resize
image_size: &image_size 224

# transform 관련
transform:
  Resize:
    width: *image_size
    height: *image_size

# 학습 관련 하이퍼파라미터
lr: 5e-5
weight_decay: 1e-6

max_epoch: &max_epoch 100

early_stopping:
  patience: 35
  delta: 0.0001

# loss 관련 설정
loss: 
  type: CombineLoss             # CombineLoss / Default
  loss_list: [binary_cross_entropy_with_logits, dice]
# loss에 필요한 parameter -> dict 형태로 작성
loss_parameter: {}

# scheduler 관련 설정
scheduler_name: CosineAnnealingWR

# scheduler 필요한 parameter -> dict 형태로 작성
scheduler_parameter:
  T_0: 20 # 웜업
  T_mult: 2 # 주기? 곱셈해서 하는거 
  eta_min: 1e-6 #최소 러닝레이트

# random seed값
seed: 21

# validation 관련 인자
val_interval: 1

# checkpoint 저장 경로
save_dir: ./checkpoints/${model.model_name}

# 구글시트
google_cloud_key_path: /data/ephemeral/home/keys/google_key.json

