# data 관련 설정
image_root: /data/ephemeral/home/train/DCM
fold_root: /data/ephemeral/home/folds
label_root: /data/ephemeral/home/train/outputs_json
fold_list: [2,]

# 모델명 및 사전 학습 여부
model:
  model_name: "DUCKNet"
  model_parameter:
    in_channels: 3
    classes: 29
    pretrained: True
    start_filters: 34

# batch_size
train_batch_size: 16
val_batch_size: 4
test_batch_size: 4

# image resize
image_size: &image_size 1024

# transform 관련
transform:
  Resize:
    width: *image_size
    height: *image_size

# 학습 관련 하이퍼파라미터
lr: 5e-4
weight_decay: 1e-6

max_epoch: &max_epoch 1

# loss 관련 설정
loss: 
  type: CombineLoss             # CombineLoss / Default
  loss_list: [binary_cross_entropy_with_logits, dice]
# loss에 필요한 parameter -> dict 형태로 작성
loss_parameter: {}

# scheduler 관련 설정
scheduler_name: CosineAnnealingLR

# scheduler 필요한 parameter -> dict 형태로 작성
scheduler_parameter:
  T_max: *max_epoch
  eta_min: 1e-6

# random seed값
seed: 21

# validation 관련 인자
val_interval: 1

# checkpoint 저장 경로
save_dir: "./checkpoints/${model_name}"

# mlflow
exp_name: refactor_test
run_name: test_run

# 구글시트
google_cloud_key_path: "/data/ephemeral/home/keys/google_key.json"
